"""empty message

Revision ID: f871f0f634b2
Revises: 0897850cf18a
Create Date: 2018-04-03 22:19:11.076709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f871f0f634b2'
down_revision = '0897850cf18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    ''' Upgrade from auto migration failed since we had users with no passwords.
    In dev this wouldn't matter and you could easily fix this by deleting users
    BUT in production, I think it would be best to update the actual migration
    file to create the new field without adding the non-nullable constraint,
    modify the data, and then add the constraint '''

    # op.add_column('users', sa.Column('password', sa.String(length=255),
    # nullable=False))
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
